### ISSUE TITLE
House transports user to the 0, 0, 0 coordinate

### ISSUE THREAD

**Issue by superusercode** [PokemonUnity/PokemonUnity#1]
![Capturez.PNG](https://i.imgur.com/41kzrQe.png)

* Platform: All

* Branch commit: Latest

* Steps: ?

**Comment by IIcolour** [comment]
That's just an issue on the house's door, it's assigned to transfer the player to the 0,0,0 coordinate. You can easily change the position in the inspector.

**Comment by superusercode** [comment]
I've only reopened this for reference when I get to work over spring break.

**Comment by gerd2002** [comment]
Easy fix, just lock the door and change the lock text to "Nobody lives here." PR incoming.

**Comment by MrAndesite** [comment]
Yeah, I fixed the issue in develop by just making the door locked. Fyi I haven't pushed it yet but it's really easy to fix.

**Comment by TeamPopplio** [comment]
Yeah, I fixed the issue in develop by just making the door locked. Fyi I haven't pushed it yet but it's really easy to fix.

**Comment by GMR516** [comment]
Locked in this commit.
https://github.com/PokemonUnity/PokemonUnity/pull/34
