### ISSUE TITLE
Requirements for CONTRIBUTING.md

### ISSUE THREAD

**Issue by superusercode** [PokemonUnity/PokemonUnity#10]
This issue will be used to track the ideas for what we should require from pull requests/issues. Current ideas include:

* Restrict to Unity 5.5 and above
* Stick to our issue template and a C# code style

**Comment by joseka1234** [comment]
Do you have a code style manual?.
The style of the variable names, function names, design patterns to use, etc.
Perhaps is a good idea to create one and accept only the pull request that use this guide.

**Comment by joseka1234** [comment]
I've made a change to the PokemonDatabase class to optimize a lot the access to it.
How could I make a pull request for that change?

**Comment by cataclys** [comment]
@joseka1234 answer @superusercode, he will help you ^^

**Comment by joseka1234** [comment]
Thank you @cataclys but, how can I ask him?
I'm a bit useless using the GitHub web.

**Comment by cataclys** [comment]
pm him on Discord superusercode#3623

**Comment by joseka1234** [comment]
Thanks!

**Comment by superusercode** [comment]
@joseka1234 We have no code style guide at the moment, but I usually go back and lint the code after a pull request goes through.

**Comment by ProgrammingKiddo** [comment]
I see there's _some_ documentation written for users of the framework, but _none_ for the developpers (i.e. internal functioning, class diagrams and relations...).
Is there any document hanging around that I haven't seen that describes a general picture of how all the scripts work with each other or something? Just to grab the big picture of the framework and get a hold of it, to make it easier (and faster) to start developing for it.

**Comment by DeathClown64** [comment]
hello i am interested in helping develop Pokemon unity i have 8 years of c# and unity knowledge under me i can even send some examples.

**Comment by DeathClown64** [comment]
Here is a screen shot in my game page.
