### ISSUE TITLE
Replace Beta with PR #109

### ISSUE THREAD

**Issue by herbertmilhomme** [PokemonUnity/PokemonUnity#110]
I left the project in a non functional state when i walked away, and the resolution found to fix the state of the project were more or less haphazardly done.

#109 is the continuation of where i left off, and the adequate solution to how it should've been resolved.

**Comment by GMR516** [comment]
Is this for "beta" branch, or the beta with network play? Your request is to merge it into the network play one, just wanted to double check you have the right branches. :)

**Comment by herbertmilhomme** [comment]
it's actually _is_ beta. there is no networking components attached to it. just that was the closest thing to what i had, and was still untouched. Not sure what you're doing with project or branches, but the merge you made kinda made the code more spaghetti. the goal is "separation of responsbilities" and putting everything in one pot by merging two folders i tried to keep separate, just made everything more complicated in the process. I fixed all of that, and now it's actually a lot more forgiving to end user with little understanding of what's going on.

**Comment by GMR516** [comment]
Ok.
