### ISSUE TITLE
Array Index Out of Bounds in scene overworldNW

### ISSUE THREAD

**Issue by joseka1234** [PokemonUnity/PokemonUnity#22]
**Did you search for similar issues before submitting this one?**

NO, I've tested all the other scenes and no any had the same issue.

**Describe the issue you encountered:**

When I run the scene overworldNW, I have an "Array index out of range" error. (More exactly 55 errors like this).
I've added some lines to the code in MapCollider.cs to test that issue and I've found that the issue happens always with z = 72.

**Expected behavior:**

When you run the scene overworldNW, you receive an "Array index out of bounds" error.

- Platform (Win 10):

Windows 10 64 bit

- Branch commit SHA:

I didn't create any branch.

- Steps to reproduce:
    1. Just run the scene overworldNW

- Screenshot if needed (error files can be attached):

Screenshot of the error and some Logs made by me.

![issuecaptura1](https://user-images.githubusercontent.com/849347/27381501-58814aa0-5683-11e7-9190-86715cede973.PNG)

Screenshot of the lines added to MapCollider.cs to test the error.

![issuecaptura2](https://user-images.githubusercontent.com/849347/27381502-5885e196-5683-11e7-9ef3-3fb3ad4cb353.PNG)

**Comment by superusercode** [comment]
@joseka1234 Can you compile #24 and see if it fixes any issues for you?

**Comment by joseka1234** [comment]
I have the error yet.

**Comment by mjohn314** [comment]
I'm not getting the error anymore on my local project with it. It might not be uploading to git correctly since the project is binary files? Is there a reason for using binary instead of text with git? Usually unity projects use text...

**Comment by superusercode** [comment]
@mjohn314 The unity files are scenes, is there a way to make them text?

**Comment by mjohn314** [comment]
@superusercode yes, in the unity editor go to edit > project settings > editor. Then under asset serialization, change the mode to force text.

**Comment by rogersachan** [comment]
@mjohn314 @superusercode We've tried that before. Turning all of the scenes to text causes weird issues, and 2017.1 seems to compound that. I'll look into this later this week and see what can be done.

**Comment by GMR516** [comment]
Fixed.
https://github.com/PokemonUnity/PokemonUnity/pull/33
