### ISSUE TITLE
English Text & Translations Is Poorly Written

### ISSUE THREAD

**Issue by herbertmilhomme** [PokemonUnity/PokemonUnity#70]
**Describe the issue**
Problem is the language xml file in the translation folder for English scripts/text is extremely sloppy, and needs to refined better. 

**Expected behavior**
Easier to navigate

**Screenshots**

**Additional context**
Looking for something that makes sense, is organized, and easily understood... without changing from xml to json (or any other format, for that matter). The problem isnt that the text doesnt load. The issue is, making sense of file is difficult, because there is no clear or easily understood pattern. Hoping someone can help by suggesting ideas, and i would implement them in future updates. 

If we can get this sorted, we can begin translating games that use this framework into multiple languages (framework already supports text, and i already have a platform for easily translating text into foreign dialects).

Thanks to any that are (or not) able to contribute.

**Comment by toxicmender** [comment]
Can you give the path/to/file for the xml file you're referring to?
Also do you mean Sanitation of the XML file or programmatic parsing of it?

**Comment by Velorexe** [comment]
The Veekun database includes every single Pokedex-, Item- and Pokemon entry, so it's possible to create a tool like the database converter to create the translation file.

**Comment by herbertmilhomme** [comment]
The game's text from UI menus to npc scripts are all stored in files. Their labels and identifiers are all out of whack.

![image](https://cdn.discordapp.com/attachments/342110419567116288/536522385117937664/unknown.png)

Need new hierarchy chart to sort how best to handle and sort out the different elements needed to be monitored. And also how to handle different versions of the same scripts. (Pokemons of different generations have their own way of saying the same messages. I had implemented some generation designs for a few things, but not all of it is commonly shared among older and new versions).

![image](https://cdn.discordapp.com/attachments/342110419567116288/536524235066179595/unknown.png)

How should we handle different story plots (npc scripts) from gen 1 (ex: professor oak lecture) to gen 5 (professor birk lecture). Do we just make a label called "Plot/Story" and then sort it by generations underneath?... do we sort and filter by npc labels/identifiers (first)? Do we ignore and give up on certain features, and leave that up to future developers? Or maybe just design static language interface for certain parts of the game, and then have the "simpler" sections translate-able...

![image](https://cdn.discordapp.com/attachments/342110419567116288/536522571517132810/unknown.png)

Questions and concerns arent complicated, they're just asking how should we view the text the users are exposed to. So it isn't an issue for anyone else, there's always a point where we can just ignore this, and push out a sloppy file, that someone will eventually have to go thru and rewrite, because it didnt make enough sense (to them).

![image](https://cdn.discordapp.com/attachments/342110419567116288/536522801050419202/unknown.png)
