### ISSUE TITLE
Rename PKU Beta to API?

### ISSUE THREAD

**Issue by herbertmilhomme** [PokemonUnity/PokemonUnity#79]
**Is your feature request related to a problem? Please describe.**
A lot of users view pokemon unity framework as if it were a game development project, when in actuality it's a framework for users to apply their _own_ skills to develop a game using tools that reduce repetitive work and tedious labor. It's not a "game" so there is no, "when are we going to be able to play it?" questions that should be asked/answered, and more... "when will it work for this _[insert something visual a user has created, example: **a map**]_ that i made?" 

The whole reason and purpose behind a "demo" is not to say: "this is the game we're making" but to express "this is something YOU can make too, if you applied this to _your project_"

**Describe the solution you'd like**
Maybe instead of calling it a "framework" (which may hold a bit of confusion in it's own way), we just call it an "API" instead? At least then, when we say "this is unstable" it can better translate from "it doesnt work for your needs" to a better statement that resembles "it isnt giving the correct results it should right now." 

**Describe alternatives you've considered**
I've considered PKU building both sides of a project (the front-end and back-end). But it's extremely difficult to focus on both sides simultaneously, without having any set blueprints or our layouts in place (considering all the different opinions and various options on how to approach things). For a while the project hasnt made a lot of progress on front-end side of things. Maybe it might be best to leave the creative input in the hands of the end-user, instead of the PKU develop team deciding in stone how things should be done?

Maybe it might be best to use GitHub to offer the connections and channels that a lot of users are lacking and in-demand of: source code and backend developers. Every time a new pokemon project is started, they're immediately done in secrecy, so their code isnt shared, and every project is in need of a developer/programmer (because finding someone capable of committing to something of this magnitude for an indefinite amount of time is also a challenge).

**Additional context**
At this point, PKU Beta is capable of supporting MANY scenarios and project application. But the obstacle that's keeping users from moving forward is that they're waiting for a "complete" product to be shipped, when the product itself requires end-users to do their part as well. The demo is only a "sample" to say "this is how *we* did thing", but the end user doesnt have to replicate our approach. They can do things their own way, and just apply our work to their progress. (That way it's like having your own development team of programmers, when you know absolutely nothing about programming).

**Comment by AriesPlaysNation** [comment]
PKU API? Or simply PokemonUnityAPI or something or other. Then gotta deal with if people understand what an API is (again having to show it's not a game development)?

**Comment by TeamPopplio** [comment]
To me, an api sounds like a service to integrate with another program the end user is developing. A framework to me sounds like something that would be the basis for the said program and something to develop onto. At least, that's how I personally see it. The name of it seems to fit more as I see it as a franework.

**Comment by herbertmilhomme** [comment]
@GMR Considering I've only invested most of my attention and work into subroutines and protocols, I say it kinda does qualify. The entire commit I made was purely backend utilities separated from unity. So all users would be required to do is make calls to the back-end and fetch data to be displayed on front.

**Comment by mhorger3** [comment]
Whenever I think of an API, my mind immediately jumps to REST Services and integrations into business applications. While @GMR516 raises a good point about the definition of what an API is, @herbertmilhomme is absolutely correct that it should be classified as an API. However, should you call it this? Probably not, because you want to stay focused for your end goal. Leaving it as an API or even a "Studio" (I think GameMaker) detracts from the vision of the project.
