### ISSUE TITLE
Sprites are getting mangled - allow users to toggle off

### ISSUE THREAD

**Issue by superusercode** [PokemonUnity/PokemonUnity#8]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Sprites are being deformed by camera in preview, but look fine in editor.
**Expected behavior:**
Editor sprites should look exactly like preview sprites.
- Platform (Win7, 8, 10? macOS? Linux distro? WebGL?):
All
- Branch commit SHA:
Latest
- Steps to reproduce:
    1. Find moving trainer
    2. stop moving
    3.

- Screenshot/gif/video if needed (error files can be attached):
![7eda2143da0830f11606db99bf7a7778](https://cloud.githubusercontent.com/assets/23001825/23238659/041ddd2a-f931-11e6-980a-326f672178c3.gif)

- Any related issues:

**Comment by superusercode** [comment]
@IIcolour Do you know about the origin/extent of this bug?

**Comment by superusercode** [comment]
Also happens with static sprites while character moves
![image](https://cloud.githubusercontent.com/assets/23001825/23238909/548843ee-f932-11e6-935b-611d7eb53abe.png)

**Comment by rogersachan** [comment]
@superusercode Your second gif is bad

**Comment by GiggleX** [comment]
Fixed it. 
Before: https://gyazo.com/1151fbe625398cf90ede754daa06722e
After: https://gyazo.com/a5e2cfd95bb35a09c8d0d2ac2e6f9fd5

I do not know what the dev intended to do here, but this just doesn't work. It's the Cameras Target Texture that causes this problem. There are currently 2 problems occuring when removing the Target Texture:
1. GUI Elements are displaced and way too small on screen
2. Sometimes texture edges occur on the floor, leaving weird lines inbetween tiles (are removed when moving again).

**Comment by GMR516** [comment]
Fixing this will probably require a full rework of all the overworld graphics.

**Comment by rogersachan** [comment]
I think this is more or less native behavior/works as intended, but if we can make it toggleable I'll make it so.

**Comment by Eternion** [comment]
Just create 2 camera with different resolution

**Comment by Eternion** [comment]
One in 392x194 for the ui and the other a resolution of your choice

**Comment by TeamPopplio** [comment]
I should write something about this, the dev (@IIcolour ) intended the framework to use an NDS resolution (albeit widesceen) as it is attempting to recreate the look of the original HGSS games. This feature is easily disable-able via the Camera rendertexture (Assets/Camera) by setting the resolution to something reasonable for your purposes. In develop, you can enable the debug feature for a higher resolution as a more accessible option.
The UI is not supported by this increase in resolution and you may see occasional errors such as this:
![image](https://user-images.githubusercontent.com/25839651/35620253-74a8011c-0635-11e8-842d-c116963ffc26.png)

If you're willing to fix this issue for the stock framework itself, keep in mind that you should not change the resolution of the UI. @Eternion does have the right idea in mind and I may consider implementing it into future commits involving master **&** develop.

**Comment by GMR516** [comment]
How much of a time investment is this to re-code the entire GUI into a canvas-based approach instead of the legacy GUI code?

**Comment by Eternion** [comment]
To fix that you must create 2 distinct views one for the game and another for the gui and the a third for a general view

**Comment by Eternion** [comment]
What I mean by view is camera

**Comment by herbertmilhomme** [comment]
There's definitely no need for multiple cameras configured at defined resolutions, with canvas (to replace obsolete legacy gui) as a solution. The canvas can scale, and snap, so cropping and stretching concerns become moot points. Which also means that different camera sizes, and view ports no longer need a given preset, since the scaling can confirm to different aspect ratios. 

@Eternion is correct, you only need 2 layers. One for canvasUI and the other for regular gameplay. the canvas sits on top of gameplay, and displays on/in the camera.
